/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer money between two accounts
         * @description Destination is either destinationAccountId or destinationAccountNumber, never both. Transfers above the step-up threshold require a recent MFA elevation (POST /api/v1/auth/step-up) or fail with 403 step-up-required.
         */
        post: operations["transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transfers/scheduled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schedule a future-dated transfer between two accounts
         * @description Only supports destinationAccountId (not destinationAccountNumber). Runs on an hourly-scheduled batch once scheduledFor is due; step-up elevation is not checked for scheduled transfers.
         */
        post: operations["scheduleTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every payee saved by the authenticated customer */
        get: operations["listPayees"];
        put?: never;
        /** Save a payee for the authenticated customer */
        post: operations["addPayee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the authenticated user's own password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/step-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Elevate the current session with a fresh MFA code
         * @description Required before a transfer at or above the step-up threshold will be accepted.
         */
        post: operations["stepUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new customer and user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate an access/refresh token pair
         * @description Reusing an already-rotated refresh token is treated as theft: it revokes the entire token family, including the legitimately-rotated successor.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete login for an MFA-enrolled user
         * @description Exchanges the mfaToken challenge from POST /api/v1/auth/login plus a TOTP or single-use recovery code for real access/refresh tokens.
         */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin TOTP enrollment
         * @description Returns a new secret and otpauth:// URI (render as a QR code); not yet active until confirmed via POST .../enroll/confirm.
         */
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enroll/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm TOTP enrollment with a code from the authenticator app
         * @description Activates MFA and returns one-time recovery codes - shown to the user exactly once.
         */
        post: operations["confirmEnroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Idempotent - an unknown or already-revoked token still returns 204.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Repeated failures trip a rate limit and lock the account (429/423-style lockout surfaced as 401 on subsequent attempts). If MFA is enabled, returns a challenge status instead of tokens - see LoginResponse.status.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every account owned by the authenticated customer */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Open a new account for the authenticated customer
         * @description The account is always opened for the caller's own customer - there is no way to open an account for anyone else.
         */
        post: operations["openAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw from an account owned by the authenticated customer
         * @description Blocked with 409 if the account isn't ACTIVE (e.g. FROZEN).
         */
        post: operations["withdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deposit into an account owned by the authenticated customer
         * @description Allowed even on a FROZEN account - only debits (withdrawals, transfers) are blocked.
         */
        post: operations["deposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/accounts/{accountId}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Freeze an account
         * @description Not scoped to any particular customer - an admin may freeze any account by id.
         */
        patch: operations["freeze"];
        trace?: never;
    };
    "/oauth2/jwks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public JSON Web Key Set
         * @description Public key material only - safe to expose without authentication, used by resource servers/clients to verify access-token signatures.
         */
        get: operations["jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated user's own identity
         * @description Resolved entirely from the JWT subject - never from a client-supplied id.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated user's own active sessions (refresh tokens)
         * @description No device/IP metadata is stored, so a 'this device' flag can't be shown - only issued/expiry times.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/login-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cursor-paginated login history for the authenticated user
         * @description Keyset pagination: pass the previous page's nextCursor to fetch the next page. Scoped to the caller's own auth-relevant events only.
         */
        get: operations["loginHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run a full ledger reconciliation check
         * @description Verifies every currency's ledger entries sum to zero and every account balance matches its ledger entries. Also runs hourly on a schedule.
         */
        get: operations["reconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health-check-style ping proving RBAC works
         * @description ROLE_ADMIN only.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cursor-paginated audit event log
         * @description Keyset pagination: pass the previous page's nextCursor to fetch the next page.
         */
        get: operations["auditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one account owned by the authenticated customer
         * @description Returns 404 (not 403) for a cross-customer accountId - existence is never leaked. Supports conditional GETs via ETag/If-None-Match.
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a cursor-paginated statement of ledger entries for one account
         * @description Keyset pagination: pass the previous page's nextCursor to fetch the next page.
         */
        get: operations["getStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/statement/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a full-range statement as CSV or PDF
         * @description Unpaginated - returns every entry in [from,to], capped at 10,000 rows; narrow the range if the cap is exceeded.
         */
        get: operations["exportStatement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payees/{payeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a payee owned by the authenticated customer
         * @description Returns 404 (not 403) for a cross-customer payeeId - existence is never leaked.
         */
        delete: operations["deletePayee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the authenticated user's own sessions
         * @description Idempotent - an unknown or already-revoked session id still returns 204, same as logout. A session id belonging to another user returns 404, not 403 - existence is never leaked.
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details, as produced by every error response in this API. */
        ProblemDetail: {
            /**
             * Format: uri
             * @example https://fernbank.dev/problems/insufficient-funds
             */
            type?: unknown;
            /** @example Insufficient Funds */
            title?: unknown;
            /**
             * Format: int32
             * @example 422
             */
            status?: unknown;
            /** @example Account 3c1f2e2a-... has insufficient funds */
            detail?: unknown;
            /** Format: uri */
            instance?: unknown;
            /**
             * Format: uuid
             * @description Echoes the X-Correlation-Id request header; auto-assigned if absent.
             */
            correlationId?: unknown;
        };
        MoneyDto: {
            /**
             * @description Decimal string, using the currency's own minor-unit precision (e.g. 2 places for USD) - must be strictly positive.
             * @example 125.5
             */
            amount?: string;
            /**
             * @description ISO-4217 currency code.
             * @example USD
             */
            currency?: string;
        };
        /** @description Exactly one of destinationAccountId or destinationAccountNumber must be provided, never both or neither - enforced at request-handling time, not by field validation, and rejected with a 400 bad-request if violated. */
        TransferRequest: {
            /** Format: uuid */
            sourceAccountId: string;
            /**
             * Format: uuid
             * @description Destination by account id - mutually exclusive with destinationAccountNumber.
             */
            destinationAccountId?: string;
            /** @description Destination by account number - mutually exclusive with destinationAccountId. */
            destinationAccountNumber?: string;
            amount: components["schemas"]["MoneyDto"];
            description?: string;
        };
        TransferResponse: {
            /** Format: uuid */
            transactionId?: string;
            /** Format: uuid */
            sourceAccountId?: string;
            sourceNewBalance?: components["schemas"]["MoneyDto"];
            /** Format: uuid */
            destinationAccountId?: string;
            destinationNewBalance?: components["schemas"]["MoneyDto"];
            /** Format: date-time */
            executedAt?: string;
        };
        ScheduleTransferRequest: {
            /** Format: uuid */
            sourceAccountId: string;
            /** Format: uuid */
            destinationAccountId: string;
            amount: components["schemas"]["MoneyDto"];
            description?: string;
            /**
             * Format: date-time
             * @description Must be in the future.
             */
            scheduledFor: string;
        };
        ScheduledTransferResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sourceAccountId?: string;
            /** Format: uuid */
            destinationAccountId?: string;
            amount?: components["schemas"]["MoneyDto"];
            description?: string;
            /** Format: date-time */
            scheduledFor?: string;
            /** @enum {string} */
            status?: "PENDING" | "EXECUTED" | "FAILED" | "CANCELLED";
        };
        PayeeRequest: {
            name?: string;
            /**
             * @description IBAN-shaped account number.
             * @example FB1234567890123456789012
             */
            targetAccountNumber?: string;
        };
        PayeeResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            targetAccountNumber?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ChangePasswordRequest: {
            currentPassword?: string;
            /** @description Minimum 8 characters. */
            newPassword?: string;
        };
        StepUpRequest: {
            code?: string;
        };
        StepUpResponse: {
            accessToken?: string;
        };
        RegisterRequest: {
            fullName?: string;
            email?: string;
            /** @description Minimum 8 characters. */
            password?: string;
        };
        RegisterResponse: {
            /** Format: uuid */
            userId?: string;
            email?: string;
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        MfaVerifyRequest: {
            mfaToken?: string;
            code?: string;
        };
        LoginResponse: {
            /** @enum {string} */
            status?: "AUTHENTICATED" | "MFA_REQUIRED";
            accessToken?: string;
            refreshToken?: string;
            mfaToken?: string;
        };
        MfaEnrollResponse: {
            secret?: string;
            otpAuthUri?: string;
        };
        MfaEnrollConfirmRequest: {
            code?: string;
        };
        MfaEnrollConfirmResponse: {
            recoveryCodes?: string[];
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        OpenAccountRequest: {
            /** @enum {string} */
            type: "CHECKING" | "SAVINGS" | "SYSTEM";
            currency?: string;
        };
        AccountResponse: {
            /** Format: uuid */
            id?: string;
            accountNumber?: string;
            /** @enum {string} */
            type?: "CHECKING" | "SAVINGS" | "SYSTEM";
            /** @enum {string} */
            status?: "ACTIVE" | "FROZEN" | "CLOSED";
            balance?: components["schemas"]["MoneyDto"];
            /** Format: date-time */
            createdAt?: string;
        };
        DepositWithdrawRequest: {
            amount: components["schemas"]["MoneyDto"];
            description?: string;
        };
        MoneyMovementResponse: {
            /** Format: uuid */
            transactionId?: string;
            /** Format: uuid */
            accountId?: string;
            newBalance?: components["schemas"]["MoneyDto"];
            /** Format: date-time */
            executedAt?: string;
        };
        FreezeAccountRequest: {
            reason?: string;
        };
        MeResponse: {
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            customerId?: string;
            email?: string;
            fullName?: string;
        };
        SessionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        AuditEventResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            actorUserId?: string;
            eventType?: string;
            metadata?: {
                [key: string]: Record<string, never>;
            };
            /** Format: date-time */
            createdAt?: string;
        };
        CursorPageAuditEventResponse: {
            data?: components["schemas"]["AuditEventResponse"][];
            nextCursor?: string;
            hasNext?: boolean;
        };
        ReconciliationDiscrepancy: {
            description?: string;
        };
        ReconciliationReport: {
            discrepancies?: components["schemas"]["ReconciliationDiscrepancy"][];
            healthy?: boolean;
        };
        CursorPageStatementEntryResponse: {
            data?: components["schemas"]["StatementEntryResponse"][];
            nextCursor?: string;
            hasNext?: boolean;
        };
        StatementEntryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            transactionId?: string;
            /** Format: date-time */
            createdAt?: string;
            amount?: components["schemas"]["MoneyDto"];
            description?: string;
        };
    };
    responses: {
        /** @description Malformed request - bad input shape, missing header, or a business rule that isn't a field-level validation failure. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Request failed Bean Validation; the response's `errors` extension lists each field error. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Missing, expired, tampered, or otherwise invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Authenticated, but not permitted to perform this action (wrong role, or step-up elevation required). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The resource doesn't exist, or exists but isn't owned by the authenticated customer - identical response either way, so existence is never leaked. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The resource is not in a state that allows this operation, or the same Idempotency-Key was reused with a different request body. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description The request is well-formed but violates a domain rule (e.g. insufficient funds, currency mismatch). */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description An unexpected server error. Never includes a stack trace or SQL - correlate via `correlationId`. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    transfer: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Transfer applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransferResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    scheduleTransfer: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleTransferRequest"];
            };
        };
        responses: {
            /** @description Transfer scheduled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduledTransferResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    listPayees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The customer's saved payees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PayeeResponse"][];
                };
            };
        };
    };
    addPayee: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayeeRequest"];
            };
        };
        responses: {
            /** @description Payee saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PayeeResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["Conflict"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    stepUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpRequest"];
            };
        };
        responses: {
            /** @description Elevated access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StepUpResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["Conflict"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A new access/refresh token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TOTP secret and otpauth URI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MfaEnrollResponse"];
                };
            };
        };
    };
    confirmEnroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaEnrollConfirmRequest"];
            };
        };
        responses: {
            /** @description MFA activated; recovery codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MfaEnrollConfirmResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token revoked (or already wasn't valid) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated, or an MFA challenge issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"][];
                };
            };
        };
    };
    openAccount: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenAccountRequest"];
            };
        };
        responses: {
            /** @description Account opened */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["Conflict"];
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositWithdrawRequest"];
            };
        };
        responses: {
            /** @description Withdrawal applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MoneyMovementResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableContent"];
        };
    };
    deposit: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositWithdrawRequest"];
            };
        };
        responses: {
            /** @description Deposit applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MoneyMovementResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    freeze: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-generated UUID. Replaying the same key with the same request body returns the original response unchanged; the same key with a different body is a 409.
                 * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
                 */
                "Idempotency-Key": string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FreezeAccountRequest"];
            };
        };
        responses: {
            /** @description Account frozen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current public JWK set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    loginHistory: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                cursor?: string;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageAuditEventResponse"];
                };
            };
        };
    };
    reconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconciliation report, healthy or listing discrepancies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReconciliationReport"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pong */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    auditEvents: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                cursor?: string;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageAuditEventResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: {
                /** @description ETag from a previous response; a match returns 304 with no body */
                "If-None-Match"?: string;
            };
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account, with an ETag header */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Not Modified - the supplied If-None-Match matches the current ETag */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getStatement: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                cursor?: string;
                pageSize?: number;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of statement entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursorPageStatementEntryResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportStatement: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                /** @description csv or pdf */
                format?: string;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exported statement file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePayee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payeeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payee deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked (or already wasn't active) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
