global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fernbank-backend
    metrics_path: /actuator/prometheus
    basic_auth:
      username: prometheus
      password: prometheus
    static_configs:
      - targets: ["backend:8080"]
